### ISSUE TITLE
Default terminal instead of gnome-terminal (Linux)

### ISSUE THREAD

**Issue by varemenos** [misfo/Shell-Turtlestein#43]
Referring to `ctrl + alt + shift + C`'s Linux keybinding

It shouldn't load `gnome-terminal` by default (not every linux distribution has gnome-terminal, nor some of us want it as the default).

I'm pretty sure there are quite a few ways to get the name of the terminal and then execute it (though i lack the knowledge). You can get the name of the default terminal by executing this command `gsettings get org.gnome.desktop.default-applications.terminal exec` but it still requires Gnome.

**Comment by stegrams** [comment]
I m not sure how feasible it is, but it would be helpful to have a user setting for the terminal name e.g.
```javascript
"comspec": "gnome-terminal"
```
