### ISSUE TITLE
Shell_cmd or cmd is required error

### ISSUE THREAD

**Issue by lmartins** [misfo/Shell-Turtlestein#55]
Im getting the following:

```
shell_cmd or cmd is required
[cmd: ]
[dir: /Users/luismartins/Sites/webipack018/themes/front]
[path: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin]
[Finished]
```

am I missing something on my configuration?

**Comment by bryansray** [comment]
I'm still seeing this issue. I was able to solve it by entering this in to the Dart.sublime-build file.

    "cmd": ["dart", "$file"]
