### ISSUE TITLE
Feature Request:  Path Follows Open Files

### ISSUE THREAD

**Issue by vasiliyb** [misfo/Shell-Turtlestein#56]
Folks, any way we can have the current working directory be the same as the file that is open?

For example, if you have several files open from several projects, it would be nice to have the shell pickup the current working directory of each file as you hit Shift+Command+C

**Comment by misfo** [comment]
This *is* how it works if the window doesn't have a directory open in the sidebar. Is that not the behavior you're seeing?

**Comment by Pastafarianist** [comment]
Can I get this behavior even when there is a directory in the side bar?

**Comment by misfo** [comment]
You can't make it work that way now. The idea was that if you have a
directory open then there's and obvious choice for the working directory of
the commands. If you have a compelling use case, though, (and want to write
the code) I'd be happy to merge in a toggleable version of the behavior
you're describing

**Comment by laggingreflex** [comment]
I'm not seeing this behavior. Whatever directory the currently opened/focused file is in, ShellTultlestein still always [shows](https://raw.githubusercontent.com/misfo/Shell-Turtlestein/master/img/input.png) and executes command in the project root.

Windows 10, ST3 (3103)

**Comment by laggingreflex** [comment]
I notice that [this:](https://github.com/misfo/Shell-Turtlestein/blob/master/shell_turtlestein.py#L17)

    folders = window.folders()

always return the project dir (as a single element in an array), even when I invoke shellturtlesetin from a file that's deep inside the project structure. Does this behave differently for you?

**Comment by misfo** [comment]
This comment explains how the directory is supposed to be chosen:
https://github.com/misfo/Shell-Turtlestein/blob/master/shell_turtlestein.py#L10-15

**Comment by misfo** [comment]
@laggingreflex contributed this feature (!) and I just merged it in. It adds a configuration option named `prefer_active_view_dir`. Enjoy!
