### ISSUE TITLE
Bind a command to key combination

### ISSUE THREAD

**Issue by smartFunX** [misfo/Shell-Turtlestein#62]
How can I define a hotkey for a particular command?
e.g. Press alt+t executes git branch

**Comment by cperryk** [comment]
I was wondering this myself and found you can do this easily enough without Shell-Turtlestein just by editing your user key bindings file. Here's an example binding:

```
{ "keys": ["command+shift+a"], "command": "exec", "args": { "cmd": ["gulp prev --cwd"], "shell":true, "path":"/usr/local/bin"}}
```

For more info see: http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/build_systems/exec.html
