### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by pakcheong** [misfo/Shell-Turtlestein#63]
I tried using "grunt" but it says "/bin/sh: grunt: command not found". But when I "CD" to the project from a terminal and used "grunt" command, it worked fine. It goes the same for "bower". But built-in commands like "CD", "LS" are working fine in your plugin. How do I fix it?

**Comment by jbrooksuk** [comment]
Install this [plugin](https://packagecontrol.io/packages/Fix%20Mac%20Path)?
