### ISSUE TITLE
End session [feature-request]

### ISSUE THREAD

**Issue by laggingreflex** [misfo/Shell-Turtlestein#68]
If you run a command and hit <kbd>Esc</kbd> the shell keeps running in the background to let the command finish. Sometimes it's good that it does that, but other times it's a nuisance. There should be an option to let the user choose which behavior they want. Better yet, a user could configure <kbd>Esc</kbd> for current default behavior (let run in background) and <kbd>Shift+Esc</kbd> to force exit the shell.

**Comment by misfo** [comment]
The actual execution of commands that aren't piped back into a view are
done as though it's a standard Sublime build system. And I think build
system's have a way to terminate early. Check Sublime's documentation for
that

**Comment by laggingreflex** [comment]
oh wow I didn't know that. That is perfect! There's a `tools > cancel build` option to do just that. And also a "show build results" to bring back an accidentally closed results window (something I thought should be a feature as well). Thanks!!

**Comment by misfo** [comment]
Happy to help :)
