### ISSUE TITLE
How to use /bin/zsh instead of /bin/sh or /bin/bash?

### ISSUE THREAD

**Issue by t-scutulatus** [misfo/Shell-Turtlestein#74]
Briefly,

Thanks for such a great package, it helps a lot.

I want to use some aliases sourced from my .zshrc file.  However, ST3 still uses /bin/sh.  What I want is to override /bin/sh with /bin/zsh so that I can use my zsh aliases.

Here's my config:

```
{
    "surround_cmd": ["source ~/.zshrc && ", ""],
    "exec_args": {},
    "cmd_settings": [],
    "input_widget": {
        "syntax": "Packages/ShellScript/Shell-Unix-Generic.tmLanguage"
    }
}
```

Here's the error from console after pressing Ctrl+C:

> ~/.zshrc: line 12: autoload: command not found
> ~/.zshrc: line 31: syntax error near unexpected token `('
> ~/.zshrc: line 31:`for config_file ($ZSH/lib/*.zsh); do'
> /bin/sh: g: command not found
> [Finished in 0.0s with exit code 127]
> [cmd: source ~/.zshrc && g]
> [dir: /home/scutulatium]
> [path: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl]

**Comment by misfo** [comment]
Looks like it's still getting evaluated by `/bin/sh`. You might be able to
change the shell that Sublime Text uses, but that'd be a Sublime config and
not a config for this plugin. Hope that helps!
